### ISSUE TITLE
Show outlines for transparent buildings

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer#24]
Currently, it can be a bit difficult to judge things like depth with how transparent buildings are currently rendered. Adding a white outline similar to the black one on opaque buildings seems to help.

Take a look at the below and see if we'd like to show the white outline (or perhaps some other color) for transparent buildings.

## Without Outline (Current)
![without-outline](https://user-images.githubusercontent.com/54951512/113615372-c948a300-9621-11eb-9ef1-6f0ebc7f8b47.png)

## With Outline (Proposed)
![with-outline](https://user-images.githubusercontent.com/54951512/113615466-e7160800-9621-11eb-8747-9977c98fb4d2.png)

**Comment by richardrouil** [comment]
I like it. Would it be hard to make it an option? Maybe in the app settings (and possibly in a toolbar in the future)

**Comment by tomhenderson** [comment]
I like the outline (either as option or just change it to this without an option).

**Comment by bpe2** [comment]
Alright, I'll implement this with a corresponding option
