### ISSUE TITLE
Using the 3D Visualizer for viewing single 3D object

### ISSUE THREAD

**Issue by igs3000** [usnistgov/NetSimulyzer#36]
Hello Evan,

What I am asking may  be a major feature to consider implementing in the 3D visualization tool.

I already requested a [feature request ](https://github.com/usnistgov/NetSimulyzer/issues/35#issue-1032136125)related with this one. 

While I try to use a free 3D object from internet, I found that the downloaded object may be in different default orientation.
Before showing that object in our 3D scene, we have to fix its orientation. Of course, the ns-3 extension part is having option for fixing orientation. 

**But the problem is :** assuming the exact orientation angle and direction  (roll/pitch/yaw) is not that much simple - we have to “blindly” do a lot of trial and error on selecting angle and rotation axis - after that only the object will get oriented correctly on the scene.  The fact is: most of the time, I  will not be successful in orienting a object through this blind, trial and error method. 

So, for this simple orientation task, I learned to use a Blender and orient the object on x Axis (or y Axis) and then easily incorporate in my simulations.

**So, what I am expecting is :**
(Apart from loading a .json file) if there will be a separate  option for loading a single 3D model directly in the 3D visualizer , only to understand its default orientation, then it will be easy for us to select the needed angle and rotation axis to make it orient correctly in the simulation scene.

**It may seem to be a childish request. But believe me - I suffered a lot in this regard. :-)  :-)** 

Charles Pandian

**Comment by bpe2** [comment]
Hey Charles.

Well, almost a year later (sorry about that), this feature is in the `dev` branch, and It'll be out in the next release.
