### ISSUE TITLE
Restart animation after playback ends

### ISSUE THREAD

**Issue by richardrouil** [usnistgov/NetSimulyzer#43]
After the playback has ended, the "play/pause" button switches to "play". However, when clicking it, nothing happens because the time is already at the end. I suggest making the animation restart from the beginning if the user click play when the time is already at the end.

**Comment by bpe2** [comment]
This is in `dev` now. I've also changed the icon for when this happens.

![full_progress_bar](https://user-images.githubusercontent.com/54951512/165770588-a35b1abb-c633-411a-a04e-1dda4e960f4a.png)
