### ISSUE TITLE
Display Logical Links Between Nodes 

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer#45]
Currently, only physical links are displayed between two nodes
It would be useful to display logical links between nodes to represent a relationship/connection between them, for example:
* Traffic flows
* Sidelink connections between wireless nodes
* TCP connections
* WiFi association

From the module, the user should be able to:
* Show/hide the link
* set an offset/position of the line
* adjust appearance of the line:
  * Color
  * Thickness
  * Solid/Dashed

**Comment by tomhenderson** [comment]
Agreed on this, and wondering about also adding routes (multi-hop paths) to show routing paths, paths that traffic flows are actually traversing, etc.  Not sure if you consider that a separate feature request or an extension of this.

**Comment by igs3000** [comment]
Displaying this kind of links are good while visualizing wired networks.
But, I believe that displaying 'too much logical link with lines' while visualizing a wireless ad hoc network scenario will spoil the elegance of 'wireless' nature of that scenario.

> From the module, the user should be able to:
> 
> Show/hide the link
> set an offset/position of the line
> adjust appearance of the line:
> Color
> Thickness
> Solid/Dashed

This is good—So, in such case, we may use dotted lines of very light colors without disturbing the very 'wireless nature' of the scenario.

Just a thought.

**Comment by YueLester** [comment]
How is this work going? I try to show the communication process in the network. For example, the communication status between nodes or the process of sending and receiving packets can be displayed.

**Comment by bpe2** [comment]
Added in [Version 1.0.11](https://github.com/usnistgov/NetSimulyzer/releases/tag/v1.0.11)
