### ISSUE TITLE
Add a scale to the camera move speed based on the scenario size

### ISSUE THREAD

**Issue by bpe2** [usnistgov/NetSimulyzer#50]
Currently, the camera movement speed maxes out at ~0.1 units per frame. This is fine for most scenarios, but at larger sizes (100+ km) this can be a bit limiting.

Introduce some sort of scaling mechanism that adjusts the base speed when loading very large (or potentially very small) scenarios.

See: https://github.com/usnistgov/NetSimulyzer/issues/47

**Comment by igs3000** [comment]
Dear Evan Black,

Even there may be some necessity to create a much larger scenario. For example, if we need to simulate a "Spacecraft to Moon or Mars Mission", there is a possibility to simulate some communication between ground stations on Earth, satellites on Earth's Orbits, and the Spacecraft. In such a scenario, we may need to visualize even a much larger network scenario.

So, there should be a scalable method to make the scenario fit inside the NetSimulizer GUI and there should be much userfriendly manipulation on that large 3D scenario using the mouse and keyboard.

So, kindly consider such possibility also.
